# Site settings
title: re.inventions
email: re222cn@student.lnu.se
description: > # this means to ignore newlines until "baseurl:"
    This is the blog-ish page of web developer student Robert Eriksson.
    By next version I’ll write something useful here.
    Also, maybe I should get a twitter account.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: ...
github_username:  robberi

# Build settings
markdown: kramdown
